'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication7.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bkg3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bkg3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchatk_01L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchatk_01L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchatk_01R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchatk_01R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchatk_02L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchatk_02L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchatk_02R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchatk_02R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchdmg_01L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchdmg_01L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchdmg_01R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchdmg_01R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchdmg_02L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchdmg_02L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchdmg_02R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchdmg_02R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchdmg_03L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchdmg_03L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchdmg_03R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchdmg_03R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crouchR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crouchR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dmg_01L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dmg_01L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dmg_01R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dmg_01R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dmg_02L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dmg_02L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dmg_02R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dmg_02R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dmg_03L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dmg_03L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dmg_03R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dmg_03R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dmg_04L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dmg_04L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dmg_04R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dmg_04R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property explode1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("explode1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property explode2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("explode2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fights_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fights_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fights_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fights_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fights_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fights_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property idleL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("idleL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property idleR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("idleR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property intro_01R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("intro_01R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property intro_02R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("intro_02R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property intro_03R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("intro_03R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property intro_04R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("intro_04R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property intro_05R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("intro_05R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property intro_06R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("intro_06R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumpatk_01L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumpatk_01L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumpatk_01R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumpatk_01R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumpatk_02L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumpatk_02L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumpatk_02R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumpatk_02R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumping_01L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumping_01L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumping_01R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumping_01R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumping_02L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumping_02L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumping_02R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumping_02R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumping_03L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumping_03L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumping_03R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumping_03R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumping_04L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumping_04L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jumping_04R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jumping_04R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kick_01L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kick_01L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kick_01R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kick_01R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kick_02L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kick_02L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kick_02R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kick_02R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kick_03L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kick_03L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kick_03R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kick_03R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kick_04L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kick_04L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kick_04R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kick_04R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Kof() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kof", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property movelist2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("movelist2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_01L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_01L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_01R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_01R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_02L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_02L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_02R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_02R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_03L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_03L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_03R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_03R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_04L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_04L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_04R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_04R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_05L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_05L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_05R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_05R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_06L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_06L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_06R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_06R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_07L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_07L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property punch_07R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("punch_07R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_01L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_01L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_01R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_01R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_02L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_02L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_02R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_02R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_03L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_03L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_03R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_03R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_04L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_04L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_04R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_04R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_05L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_05L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_05R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_05R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_06L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_06L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reppuken_06R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reppuken_06R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property score() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("score", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property walking_01L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walking_01L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property walking_01R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walking_01R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property walking_02L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walking_02L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property walking_02R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walking_02R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
